server:
  port: 8081

spring:
  application:
    name: springboot-observability-demo

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
