<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Reliant.Worker-450416e8-e3f6-4923-9e83-801b4277c2d1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reliant.Application\Reliant.Application.csproj" />
    <ProjectReference Include="..\Reliant.Infrastructure\Reliant.Infrastructure.csproj" />
  </ItemGroup>
</Project>
